### ISSUE TITLE
Not compatible with requirejs 

### ISSUE THREAD

**Issue by gtzilla** [wavded/humane-js#49]
The current amd / node friendly definition format doesn't play well with the loading functionality of requirejs. I needed to stripe the module.exports code and directly assign window.humane = new Humane in a single closure structure. 

Here is a gist of the simplified code, sans all node js support, that works with requirejs. https://gist.github.com/gregory80/b451035746ad8479bf04

**Comment by lukemarsh** [comment]
Hi @wavded I have also found this issue. I'm requiring humane in a module and it's not working when I run my tests. The error I get is: CrudModule missing humane.

Any ideas?

**Comment by lukemarsh** [comment]
An issue was also opened in stackoverflow: http://stackoverflow.com/questions/22645225/angularjs-unit-test-referenceerror-humane-is-not-defined

**Comment by wavded** [comment]
Do you have a simple failing case that you can share?  Like a jsbin or fiddle even?

**Comment by shehi** [comment]
Let me ask this question: docs say just start like this ```var notify = humane.create(...);```... Question is: where was ```humane``` declared?! Why don't we declare it in our own code instead? PHPStorm gets crazy here, when I work on JS partials. Wouldn't it be better if we declared it ourselves?
