### ISSUE TITLE
Humane stylesheet displays scrollbars when it shouldn't

### ISSUE THREAD

**Issue by norpol** [wavded/humane-js#66]
Hi, we are running into the issue that humane setting up a [min-height of 100%](https://github.com/wavded/humane-js/blob/1fd4bcd1231437d23e8f9d5f86bb5226fb2236ad/theme-src/original.styl#L5) , I can't see why this is usable at all. Maybe you? Can it be removed?

**Comment by wavded** [comment]
I honestly cannot remember why I put that in there.  Does it behave appropriately if you remove it?

**Comment by norpol** [comment]
Hi! Thank's for your reply. Yes it does work's if I overwrite it. `min-height` makes only sense for me when testing humane-js on a blank html page, but it even doesn't make sense there. :) Only thing I could find in the history was https://github.com/wavded/humane-js/pull/25 .
I guess you can remove it and hope it won't break any other's setup - but I personally don't think that this might become an issue for others.
Cheers :+1:  :) Thank's for open source software <3.
