### ISSUE TITLE
Adding hyperlinks to notification?

### ISSUE THREAD

**Issue by jacobpatton** [wavded/humane-js#73]
Is there a way to add clickable hyperlinks to the Humane notifications?

I've tried simply adding the links to the notification text, but although they appear in the notification, they're not clickable — even if I disable dismissing the notification on-click.

**Comment by wavded** [comment]
Yes, because of `pointer-events: none` you cannot use links within the HTML.  The design decision here is to keep the notification unobtrusive.  So links behind it could still be accessed.  That said, you could make a theme that removes that style rule and use links.

**Comment by jacobpatton** [comment]
Gotcha, thanks @wavded
