### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by edouard-lopez** [wavded/humane-js#74]
On the [github.io page](https://wavded.github.io/humane-js/) you stated

> A simple, modern, framework-independent, well-tested, unobtrusive, notification system. 

But I see no `test` script in your project. Please add (unit) tests

**Comment by wavded** [comment]
Although this project does not have a `test` script, I can assure you it has been "well-tested" manually (the old-fashioned way) within browsers (mobile and desktop) to ensure its behavior is as documented as well as a lot of airtime in production websites.  Including specific bug behavior tests in the `test` directory.  Given the popularity of the project and the lack of open bugs should support this.  The core has remained unchanged for quite some time now (Dec 8, 2014) and I have no plans on adding any new functionality, only addressing any new bugs that may arise on a case by case basis.
